#!/usr/bin/env python3
"""Measure how much the twist cleanup (`--op twist`) changes the boxing clips.

For each boxing GLB regenerated by parity_gate.py (build/parity/raw), run the
CLI twice: the boxing preset alone, and the boxing preset plus `--op twist`
(optionally with `--twist TOL_DEG:SHARE`). For every knee and elbow, compare
the two outputs per frame and report:

  off      off-hinge angle of the source (deg) about the clip's mean hinge axis
  touched  share of frames whose rotation changed by more than 0.05 deg
  removed  median / p95 / max rotation removed (deg)

Writes build/twist-audit/report.json. Read only on sources.
"""
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from parity_gate import load, accessor, ROOT, CLI, CHARACTERS  # noqa: E402

OUT = ROOT / "build/twist-audit"
JOINTS = ["mixamorig:LeftLeg", "mixamorig:RightLeg", "mixamorig:LeftForeArm", "mixamorig:RightForeArm"]


def qmul(a, b):
    ax, ay, az, aw = a.T
    bx, by, bz, bw = b.T
    return np.stack([aw * bx + ax * bw + ay * bz - az * by,
                     aw * by - ax * bz + ay * bw + az * bx,
                     aw * bz + ax * by - ay * bx + az * bw,
                     aw * bw - ax * bx - ay * by - az * bz], axis=1)


def conj(q):
    return q * np.array([-1.0, -1.0, -1.0, 1.0])


def angle(q):
    return np.degrees(2.0 * np.arccos(np.clip(np.abs(q[:, 3]), 0.0, 1.0)))


def tracks(path):
    doc, blob = load(path)
    names = {n.get("name"): i for i, n in enumerate(doc["nodes"])}
    out = {}
    for anim in doc["animations"]:
        for ch in anim["channels"]:
            node = ch["target"].get("node")
            if ch["target"]["path"] == "rotation" and doc["nodes"][node].get("name") in JOINTS:
                q = accessor(doc, blob, anim["samplers"][ch["sampler"]]["output"])
                rest = np.array(doc["nodes"][node].get("rotation", [0, 0, 0, 1]), dtype=np.float64)
                out[(anim["name"], doc["nodes"][node]["name"])] = (q, rest)
    return out


def off_hinge(q, rest):
    d = qmul(np.repeat(conj(rest[None]), len(q), axis=0), q)
    d *= np.where(d[:, 3:4] < 0, -1.0, 1.0)
    axes = d[:, :3].copy()
    total = np.zeros(3)
    for a in axes:
        total += -a if a @ total < 0 else a
    h = total / max(np.linalg.norm(total), 1e-12)
    # Twist about h, swing = d * twist^-1; off-hinge = swing angle.
    p = (d[:, :3] @ h)[:, None] * h
    tw = np.concatenate([p, d[:, 3:4]], axis=1)
    tw /= np.maximum(np.linalg.norm(tw, axis=1, keepdims=True), 1e-12)
    return angle(qmul(d, conj(tw)))


def main():
    extra = sys.argv[1:]
    OUT.mkdir(parents=True, exist_ok=True)
    report = {"extra_args": extra, "joints": {}}
    per_joint = {}
    for c in CHARACTERS:
        raw = ROOT / "build/parity/raw" / c / f"{c}-boxer.glb"
        if not raw.exists():
            sys.exit("run tools/parity_gate.py first (regenerates build/parity/raw)")
        base, twist = OUT / f"{c}-base.glb", OUT / f"{c}-twist.glb"
        subprocess.run([str(CLI), "clean", str(raw), str(base), "--preset", "boxing"], check=True, capture_output=True)
        subprocess.run([str(CLI), "clean", str(raw), str(twist), "--preset", "boxing", "--op", "twist", *extra],
                       check=True, capture_output=True)
        a, b = tracks(base), tracks(twist)
        for key, (qa, rest) in a.items():
            qb = b[key][0]
            removed = angle(qmul(conj(qa), qb))
            stats = per_joint.setdefault(key[1], {"off": [], "removed": []})
            stats["off"].append(off_hinge(qa, rest))
            stats["removed"].append(removed)
    print(f"{'joint':24} {'off p50':>8} {'off p95':>8} {'touched':>8} {'rm p50':>7} {'rm p95':>7} {'rm max':>7}")
    for joint, s in per_joint.items():
        off = np.concatenate(s["off"])
        rm = np.concatenate(s["removed"])
        touched = rm > 0.05
        row = {"frames": int(rm.size), "off_p50": float(np.median(off)), "off_p95": float(np.percentile(off, 95)),
               "touched": float(touched.mean()),
               "removed_p50": float(np.median(rm[touched])) if touched.any() else 0.0,
               "removed_p95": float(np.percentile(rm[touched], 95)) if touched.any() else 0.0,
               "removed_max": float(rm.max())}
        report["joints"][joint] = row
        print(f"{joint:24} {row['off_p50']:8.2f} {row['off_p95']:8.2f} {row['touched']:8.1%} "
              f"{row['removed_p50']:7.2f} {row['removed_p95']:7.2f} {row['removed_max']:7.2f}")
    (OUT / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
